# This is a basic workflow to help you get started with Actions

name: Update data from JHU CSSE

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ code ]
  schedule:
    - cron: '59 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  downloadfiles:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      wd: ./data

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: 'code'
    
    - name: check working directory
      run: |
        pwd
        ls
        
    - name: download confirmed data
      uses: wei/curl@v1.1.1
      with:
        args: -v -o ./data/time_series-ncov-Recovered.csv "$URL"
      env:
        URL: "https://data.humdata.org/hxlproxy/data/download/time_series-ncov-Recovered.csv?dest=data_edit&filter01=explode&explode-header-att01=date&explode-value-att01=value&filter02=rename&rename-oldtag02=%23affected%2Bdate&rename-newtag02=%23date&rename-header02=Date&filter03=rename&rename-oldtag03=%23affected%2Bvalue&rename-newtag03=%23affected%2Brecovered%2Bvalue%2Bnum&rename-header03=Value&filter04=clean&clean-date-tags04=%23date&filter05=sort&sort-tags05=%23date&sort-reverse05=on&filter06=sort&sort-tags06=%23country%2Bname%2C%23adm1%2Bname&tagger-match-all=on&tagger-default-tag=%23affected%2Blabel&tagger-01-header=province%2Fstate&tagger-01-tag=%23adm1%2Bname&tagger-02-header=country%2Fregion&tagger-02-tag=%23country%2Bname&tagger-03-header=lat&tagger-03-tag=%23geo%2Blat&tagger-04-header=long&tagger-04-tag=%23geo%2Blon&header-row=1&url=https%3A%2F%2Fraw.githubusercontent.com%2FCSSEGISandData%2FCOVID-19%2Fmaster%2Fcsse_covid_19_data%2Fcsse_covid_19_time_series%2Ftime_series_19-covid-Recovered.csv" 
   
    - name: download death data
      uses: wei/curl@v1.1.1
      with:
        args: -v -o ./data/time_series-ncov-Deaths.csv "$URL"
      env:
        URL: "https://data.humdata.org/hxlproxy/data/download/time_series-ncov-Deaths.csv?dest=data_edit&filter01=explode&explode-header-att01=date&explode-value-att01=value&filter02=rename&rename-oldtag02=%23affected%2Bdate&rename-newtag02=%23date&rename-header02=Date&filter03=rename&rename-oldtag03=%23affected%2Bvalue&rename-newtag03=%23affected%2Bkilled%2Bvalue%2Bnum&rename-header03=Value&filter04=clean&clean-date-tags04=%23date&filter05=sort&sort-tags05=%23date&sort-reverse05=on&filter06=sort&sort-tags06=%23country%2Bname%2C%23adm1%2Bname&tagger-match-all=on&tagger-default-tag=%23affected%2Blabel&tagger-01-header=province%2Fstate&tagger-01-tag=%23adm1%2Bname&tagger-02-header=country%2Fregion&tagger-02-tag=%23country%2Bname&tagger-03-header=lat&tagger-03-tag=%23geo%2Blat&tagger-04-header=long&tagger-04-tag=%23geo%2Blon&header-row=1&url=https%3A%2F%2Fraw.githubusercontent.com%2FCSSEGISandData%2FCOVID-19%2Fmaster%2Fcsse_covid_19_data%2Fcsse_covid_19_time_series%2Ftime_series_19-covid-Deaths.csv"  
        
    - name: download confirmed data
      uses: wei/curl@v1.1.1
      with:
        args: -v -o ./data/time_series-ncov-Confirmed.csv "$URL"
      env:
        URL: "https://data.humdata.org/hxlproxy/data/download/time_series-ncov-Confirmed.csv?dest=data_edit&filter01=explode&explode-header-att01=date&explode-value-att01=value&filter02=rename&rename-oldtag02=%23affected%2Bdate&rename-newtag02=%23date&rename-header02=Date&filter03=rename&rename-oldtag03=%23affected%2Bvalue&rename-newtag03=%23affected%2Binfected%2Bvalue%2Bnum&rename-header03=Value&filter04=clean&clean-date-tags04=%23date&filter05=sort&sort-tags05=%23date&sort-reverse05=on&filter06=sort&sort-tags06=%23country%2Bname%2C%23adm1%2Bname&tagger-match-all=on&tagger-default-tag=%23affected%2Blabel&tagger-01-header=province%2Fstate&tagger-01-tag=%23adm1%2Bname&tagger-02-header=country%2Fregion&tagger-02-tag=%23country%2Bname&tagger-03-header=lat&tagger-03-tag=%23geo%2Blat&tagger-04-header=long&tagger-04-tag=%23geo%2Blon&header-row=1&url=https%3A%2F%2Fraw.githubusercontent.com%2FCSSEGISandData%2FCOVID-19%2Fmaster%2Fcsse_covid_19_data%2Fcsse_covid_19_time_series%2Ftime_series_19-covid-Confirmed.csv"

    - name: commit download
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add ./data/*.csv
        git commit -m "Update data ..." -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{secrets.GITHUB_TOKEN}}
      
  setupR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'code'
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
     
      - name: query dependencies
        run: |
          pack <- available.packages()
          saveRDS(pack[c("flexdashboard", "dygraphs", "xts", "tidyverse", "rmarkdown"),], "depends.Rds")
        shell: Rscript {0}
          
      - name: cache dependencies
        uses: actions/cache@v1
        env:
          cache-name: cache-R-packages
        with:
          path: ${{env.R_LIBS_USER}}
          key: ${{runner.os}}-r-packages-${{hashFiles('depends.Rds')}}
          restore-keys: ${{runner.os}}-r-packages-
          
      - name: install dependencies
        run: |
          install.packages(c('flexdashboard', 'dygraphs', 'xts', 'tidyverse', 'rmarkdown'))
        shell: Rscript {0}
      - uses: actions/checkout@v2
        with:
          ref: 'code'
      - uses: r-lib/actions/setup-r@master

      - name: setupSite
        run: |
          R -e "rmarkdown::render('index.Rmd', output_file='index.html')"
          
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          
      - name: uploadSite
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add index.html
          git commit -m "Updated website with new data" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
        
          
      
          
    
